### ISSUE TITLE
Why not use pv -L ?

### ISSUE THREAD

**Issue by q2dg** [sjmulder/trickle#4]
I can't see the usefulness of trickle existing this other well-known alternative
I'd glad to be lighted.
Thanks!

**Comment by sjmulder** [comment]
I wasn't aware of this `pv` feature, thanks for mentioning it. Now I feel twofold. First, this little project is borne out of curiosity and intended to be interesting more than useful. But it's useful to me because I enjoy playing with it. In hindsight, that curiosity might have been satisfied by `pv`.

Secondly, I refer to Pike and Kerninghan's 1984 paper [_Program design in the Unix environment_](https://sjmulder.nl/dl/pdf/1984%20-%20Pike%20%26%20Kernighan%20-%20Program%20design%20in%20the%20UNIX%20environment.pdf).

It makes a case for keeping responsibilities between Unix programs separate: one program for concatenating things, another for numbering lines, and so on. In line of that thinking I feel that pipe throughput limiting is not the responsibility of a pipe visualiser and should be a different program.

Probably not `trickle` though, because that's expressly intended to only simulate very low bitrates. It doesn't account for `nanosleep()` inaccuracy or overhead either.

**Comment by q2dg** [comment]
Ok, thanks a lot for your explanation!
If you don't mind, I'll close the issue, then

**Comment by sjmulder** [comment]
Cheers!
